### ISSUE TITLE
Approve/Reject coming multiple times

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#43]
Approve/Reject coming multiple times in notification worklist

![image](https://cloud.githubusercontent.com/assets/23504285/21588258/88d38ffc-d0fe-11e6-992a-70f3dc46eac1.png)

**Comment by karthmoh** [comment]
Hi @asinghmdcbms ,

The worklist actions are populated based on the below logic.
Every notification will have the applicable actions associated to it. So, these are represented as below:

"actions": [
  {
    "id": "APPROVED",
    "title": "Approve",
......    
    
"actions": [
  {
    "id": "A",
    "title": "Approve",
......    
         
"actions": [
  {
    "id": "APPROVE",
    "title": "Approve",
......    

The grouping of actions and the count happens based on the id of the action in the above case they are 'APPROVED', 'A', 'APPROVE' and the displayed prompt is the title associated to the id(in this case all are 'Approve'). 
Since the title associated for these are same we get to see multiple Approve prompts in the UI with different counts. These values are picked up from WF_LOOKUPS for the corresponding notification id. Hence the behaviour.
Request you to review the same.

Thanks.

**Comment by duncancasemore** [comment]
@karthmoh I think we should accept this as a bug.  The flex app uses the 'title' as the id, not the actual id.  That results in a better UX.

**Comment by karthmoh** [comment]
The above issue is fixed in CRP2. This will be delivered as a hot fix. We will update the MD120 and share the same.

![wl](https://cloud.githubusercontent.com/assets/12637571/21840669/b4fb484c-d804-11e6-9229-055f229d3ce5.png)
