### ISSUE TITLE
Payslip not getting displayed correctly when using html5 version

### ISSUE THREAD

**Issue by asinghmdcbms** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#50]
Payslip not getting displayed correctly when using html5 version

![image](https://cloud.githubusercontent.com/assets/23504285/21602330/4afae82a-d1ac-11e6-9260-36fdff0b0130.png)

**Comment by hgajula-applaud** [comment]
Currently the software supports to render the Payslip display as is in the PDF for only US , UK legislation . 
If you are looking to support this for your legislation then this has to be out of SOW item otherwise you have to wait till it is available from base software itself and you can log a feature request ( SR ) .

**Comment by asinghmdcbms** [comment]
Once the solution is available in product , Applaud team needs to do setup for UAE paylsip in our test instance and provide KT for doing same setup in production. We will keep this issue as pending applaud action till then.

**Comment by hgajula-applaud** [comment]
As discussed over Management call this will be delivered in the March Public Software Release.
