### ISSUE TITLE
Provision of HTML5 .ipa and .apk files for iPhone and Android

### ISSUE THREAD

**Issue by navinw** [ApplaudSolutions/Mubadala-HTML5-Upgrade-#6]
Provision of HTML5 .ipa and .apk files for iPhone and Android, suitable for deployment to internal MDM and MAM platforms. If needed Applaud will provide guidance to Mubadala IT Team to make the new HTML5 app work in its Citrix MAM environment. 

If any code change is needed to make the mobile app work in the Mubadala environment, the same will be provided by Applaud so long as Applaud Management agrees such a change is feasible and will not affect other Applaud clients.

**Comment by asinghmdcbms** [comment]
We tried opening crp2 instance on our iPad browser  and its working all fine. However, we are facing issue with the native app.

**Comment by asinghmdcbms** [comment]
Error received is 

![image](https://cloud.githubusercontent.com/assets/23504285/21589403/bb2450ca-d10a-11e6-9de0-c1a165c8aa0e.png)

**Comment by karthmoh** [comment]
Hi @asinghmdcbms,

Could you please share the detailed steps to install and access the native app in iPAD and other devices as per our previous discussion.

Thanks.

**Comment by asinghmdcbms** [comment]
Please find below the steps. 

1)	Download app named ‘Secure Hub by Citrix’ from the appstore(for iOS) or playstore(android)
2)	Once app is installed , on opening it will ask for url/email.  Below string needs to be entered :-
  mymobile.pp.mdcbms.ae

3)	Post other steps it will ask for username and password. Enter below AD(active directory) details :-
Username : syusuf@ppcorp.ppservices.mdc
Password : asdf-0987
4)	It will also ask to set some PIN. You may enter it as 9998. Later, whenever you open app, instead of asking for username/password, it will ask for this PIN.
5)	Once above steps is done, the app will open up.
From the Store tab select apps named (1) EmpCenter (2) Secure Web
and press the Add button

6)	Step (5) will add below two icons on desktop 
   -Mubadala (this is the native app)
   -Secure Web (this is the web-browser)

  When we launch the native app it will ask for username/password. Here oracle username/password has to be entered.

For opening the app in browser, below url needs to be opened :-
http://crp2.pp.mdcbms.ae:8010

**Comment by asinghmdcbms** [comment]
Dear Hari,

We are no longer getting error . Please note we used the old apps that we had instead of downloading the one in above link.


Please let us know if apps present at above locations has any additional fixes  and if we should be using that ?

Also, can you please answer my below query in git #37 

I tried again now(launching url http://crp2.pp.mdcbms.ae:8010/OA_HTML/a/#/person-home) and instead of getting error page I got the login page. Just wanted to know if there was any fix done by Applaud to make it work ? (we had done autoconfig and middle-tier bounce in yesterday afternoon and after that we were still getting error)

**Comment by hgajula-applaud** [comment]
Yes @asinghmdcbms please use the latest apps as these has some new fixes made. 

Ans to your query : No , nothing was done apart from cache clear.

**Comment by asinghmdcbms** [comment]
https://drive.google.com/drive/folders/0B9y15Dxhu6mUOGY4aXQ0T0ljRk0

Above has URL embedded for test or prod  ?

**Comment by hgajula-applaud** [comment]
Above url provides the apps for both and the respective url is embedded as well. You just need to download the apps from that url.
